# Build and test the solver using Docker containers
name: Build and test

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        container-image:
          - name: "OpenFOAM-v2312"
            image: "opencfd/openfoam-dev:2312"
            source: "/usr/lib/openfoam/openfoam2312/etc/bashrc"
            buildflags: "-j"

    container:
      image: ${{ matrix.container-image.image }}

    steps:
      - uses: actions/checkout@v3

      - name: make
        shell: bash -l {0}
        run: |
          source ${{ matrix.container-image.source }}
          (cd src && wmake)

