name: Compile the solver

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          curl -s https://dl.openfoam.com/add-debian-repo.sh | sudo bash
          sudo apt-get install openfoam2312-default

      - name: Source OpenFOAM environment
        run: |
          echo "source /usr/lib/openfoam/openfoam2312/etc/bashrc" >> $GITHUB_ENV

      - name: Compile OpenFOAM code
        run: |
          source $GITHUB_ENV
          cd src && wmake